name: Build
on:
  push:
    tags:        
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Publish (Linux x64)
      run: dotnet publish --runtime linux-x64 -c Release
    - name: Publish (Linux arm64)
      run: dotnet publish --runtime linux-arm64 -c Release
    - name: Publish (Windows x64)
      run: dotnet publish --runtime win-x64 -c Release
    - name: Package (Linux x64)
      run: cd out-linux-x64 && tar -czf assetto-server-linux-x64.tar.gz * && cd ..
    - name: Package (Linux arm64)
      run: cd out-linux-arm64 && tar -czf assetto-server-linux-arm64.tar.gz * && cd ..
    - name: Package (Windows x64)
      run: cd out-win-x64 && zip -r assetto-server-win-x64.zip * && cd ..
    - name: Package FastTravelPlugin (Linux x64)
      run: cd out-linux-x64/plugins && zip -r ../../fasttravelplugin-linux-x64.zip FastTravelPlugin && cd ../..
    - name: Package FastTravelPlugin (Linux arm64)
      run: cd out-linux-arm64/plugins && zip -r ../../fasttravelplugin-linux-arm64.zip FastTravelPlugin && cd ../..
    - name: Package FastTravelPlugin (Windows x64)
      run: cd out-win-x64/plugins && zip -r ../../fasttravelplugin-win-x64.zip FastTravelPlugin && cd ../..
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          fasttravelplugin-linux-x64.zip
          fasttravelplugin-linux-arm64.zip
          fasttravelplugin-win-x64.zip
        body: |
          ### Changes
          Updated to AssettoServer v0.0.5
          For AssettoServer changes please check the [official release notes.](https://github.com/compujuckel/AssettoServer/releases)
          ### Installation
          > [!CAUTION]
          > **Requires the same AssettoServer version as in the release title. [Download](https://github.com/compujuckel/AssettoServer/releases)**
          1. Download and extract the `fasttravelplugin-win-x64.zip`
          2. Move the `FastTravelPlugin` folder into the `\plugins\` folder of your server.
          3. Configure the plugin, read the [wiki page.](https://github.com/C1XTZ/AssettoServer/wiki/FastTravelPlugin#plugin-configuration)
